### ISSUE TITLE
BlinkID v4.11.00 SIGABRT on iOS 12

### ISSUE THREAD

**Issue by iSapozhnik** [BlinkID/blinkid-ios#265] opened 2019-09-30 09:48 UTC
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.0 (11A420a)
  * BlinkID SDK version: v4.11.0
  * What are you trying to scan? German driving license

### [REQUIRED] Step 3: Describe the problem

On devices, running iOS 12, we have a problem that whenever we are trying to scan something it immediately throwing a SIGABRT. We don't have too much information in our logs but we have this:

```
*** Assertion failure in -[PPCameraManager setSampleBufferDelegate:queue:], /opt/jenkins-ios/E0/blinkid-ios-framework/core-ios/CommonFramework/Hardware/PPCameraManager.mm:1102
2019-09-20 15:27:24.487174+0200 App-iOS[4142:1445541] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Called while no video data output'
```

Any ideas what might be wrong?

**Comment by culoi** [comment] 2019-09-30 09:59
Hello @iSapozhnik 

Can you please share how did you implement our SDK and if you are using MBRecognizerRunnerViewController? Are you using it modally (using the present method) or you are adding it to ViewController as a child?

Under the Samples folder of our SDK, there is a demo project for the BlinkID. You can run it to test if this also happens on our default configuration: 
https://github.com/BlinkID/blinkid-ios/tree/master/Samples/BlinkID-sample-Swift

Regards

**Comment by iSapozhnik** [comment] 2019-09-30 10:44
@culoi thanks for your quick reply. While I'm checking the example app here are the answers to your questions:
- yes we are using MBRecognizerRunnerViewController
- and yes we are adding it as a child view controller

**Comment by culoi** [comment] 2019-09-30 11:12
Hi @iSapozhnik 

Is this only happening on iOS 12 devices? Is it reproducible also on iOS 13? 

Can you please share you VC so we can check it out and see what is happening? 

You can send it to our support@microblink.com email address. 

Best regards,

Ivan

**Comment by iSapozhnik** [comment] 2019-09-30 12:48
@culoi yes, this is happening only on iOS 12 devices. We also have some crashes on iOS 13 devices but much rarely. The issue I described here is happening in 100% times on iOS 12.

What do you mean by VC?

**Comment by culoi** [comment] 2019-09-30 12:53
Hi @iSapozhnik 

VC = ViewController so we can check how you impemented the code.

Maybe the issue is in the implementation. Did you manage to run the sample app and check if this also happens with our Sample app. You can download the .zip file here: https://github.com/BlinkID/blinkid-ios/releases/download/v4.11.0/blinkid-ios_v4.11.0.zip and under the Samples - BlinkID-sample-Swift, open it in Xcode and run on your iOS 12 device. 

Please let us know the results. 

Regards

**Comment by iSapozhnik** [comment] 2019-09-30 16:22
I will provide you with the details of implementation tomorrow.
I've been trying to run the example but with no luck:
![image](https://user-images.githubusercontent.com/1089384/65897325-4ea92280-e3af-11e9-9cf7-1ffa8d9ca507.png)

**Comment by culoi** [comment] 2019-09-30 17:00
Hi @iSapozhnik,

Please try to remove MicroBlink.framework and MicroBlink.bundle from your project, rename them to Microblink.framework and Microblink.bundle and include them back to and run the sample app.

More details about renaming the framework can be found in this topic: https://help.microblink.com/hc/en-us/articles/360007671300-Resource-image-not-found

Regards

**Comment by iSapozhnik** [comment] 2019-09-30 18:57
@culoi Thanks will try that in the morning

**Comment by iSapozhnik** [comment] 2019-10-01 08:24
@culoi Hey! Actually, I have noticed that the framework already has the correct name. B character is not capitalised.

**Comment by culoi** [comment] 2019-10-01 11:01
Hi @iSapozhnik 

We tried to reproduce this on a couple of laptops and without any success. 

Did you simply unpack the repo, load BlinkID-sample-Swift.xcodeproj and run it without any modifications? 

Regards

**Comment by iSapozhnik** [comment] 2019-10-01 11:08
@culoi yes, course. Ok will try to figure that out and will let you know...

**Comment by donikv** [comment] 2019-10-04 06:33
Hi @culoi,

I would just like to report that this is also happening for me, but with PPBlinkID version 4.10.0 on iOS 13. It seems to be happening when the camera controller is deallocated. (The RecognizerRunnerController is set as a child viewController). 

Best regards

**Comment by culoi** [comment] 2019-10-04 09:19
Hi @donikv,

I'm checking this with the rest of the dev team.
If you are using pauseScanning() method, resumeScanningAndResetState() needs to be called to sync counters and recognizerRunnerViewController video output. Also, that sync needs to be done on the same thread. 

I'm just guessing this, it would be helpful if you could send us your code so we can review it and see what is going on. 

I will keep you updated on this thread once we find out more info. 

Regards

**Comment by iSapozhnik** [comment] 2019-10-07 12:23
@culoi Hey again. 
So I've been playing around with the sample app from here https://github.com/BlinkID/blinkid-ios/releases/download/v4.11.0/blinkid-ios_v4.11.0.zip and the only thing I changed is the license key and the bundle id. So I just registered a new demo key for my bundle id and the steps are following: 
- tap Start Scanning 
- immediately tap on Close cross
- repeat step one...

And some moment the app crashed. Here is the log:
<details><summary>Expand</summary>
<p>

### Device: iPhone 7 plus, iOS 12

```
Error in cpuinfo: sysctlbyname("hw.packages") failed: Operation not permitted
Error in cpuinfo: sysctlbyname("hw.cacheconfig") failed: Operation not permitted
2019-10-07 14:15:06.498821+0200 BlinkID-sample-Swift[381:35024] Metal API Validation Enabled
Error in cpuinfo: sysctl("HW_L3CACHESIZE") failed: Invalid argument
[D] func [line:33] 2019-10-07 14:15:06.740463+0200 BlinkID-sample-Swift[381:35024] Unlocking BlinkID library version 4.11.0
2019-10-07 14:15:35.162552+0200 BlinkID-sample-Swift[381:35024] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2019-10-07 14:15:35.163508+0200 BlinkID-sample-Swift[381:35024] [MC] Reading from public effective user settings.
2019-10-07 14:15:48.775904+0200 BlinkID-sample-Swift[381:35024] 


 You are using time-limited license key!
2019-10-07 14:15:51.209852+0200 BlinkID-sample-Swift[381:35024] 


 You are using time-limited license key!
2019-10-07 14:16:06.992951+0200 BlinkID-sample-Swift[381:35024] 


 You are using time-limited license key!
Got EUDL image with width: 840.0, height: 530.0
2019-10-07 14:16:13.382507+0200 BlinkID-sample-Swift[381:35024] 


 You are using time-limited license key!
2019-10-07 14:16:24.226633+0200 BlinkID-sample-Swift[381:35024] 


 You are using time-limited license key!
2019-10-07 14:16:24.767222+0200 BlinkID-sample-Swift[381:35675] *** Assertion failure in -[MBCameraCoordinator pauseRecognition], /opt/jenkins-ios/E0/blinkid-ios-framework/core-ios/CommonFramework/Coordinator/MBCameraCoordinator.mm:126
2019-10-07 14:16:24.768927+0200 BlinkID-sample-Swift[381:35675] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Camera session should be started and running to pause recognition'
*** First throw call stack:
(0x1ede7127c 0x1ed04b9f8 0x1edd8a988 0x1ee84e188 0x100d36630 0x100843548 0x100d74f30 0x1008f0c74 0x1008f8bf4 0x1008f98b4 0x10090377c 0x1eda91114 0x1eda93cd4)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

</p>
</details>

**Comment by culoi** [comment] 2019-10-09 07:28
Hello @iSapozhnik,

I will forward this to our QA team. 

Let us try to reproduce it and I will contact you. Thank you for sharing the steps.

Best regards

**Comment by iSapozhnik** [comment] 2019-10-29 12:46
Hello @culoi any progress on this issue?

**Comment by culoi** [comment] 2019-10-30 11:46
Hi @iSapozhnik 

We didn't manage to reproduce this with the default bundle id and license key. Also, we tested on iOS 13.1.3 so maybe the problem is with the specific iOS version.

Please contact us to support@microblink.com with your license key and bundle id and we will try to reproduce it with your settings. 

Regards

**Comment by kikettas** [comment] 2019-11-11 14:52
Hi there!

```
*** Assertion failure in -[PPCameraManager setSampleBufferDelegate:queue:], /opt/jenkins-ios/E0/blinkid-ios-framework/core-ios/CommonFramework/Hardware/PPCameraManager.mm:1102
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Called while no video data output'
```

I'm also undergoing this issue in both 13.1 and 13.2.2. Any lead on what could be the issue?

**Comment by culoi** [comment] 2019-11-15 09:41
Hi @kikettas 

At the moment no, we do not have any information about why this issue is happening as we are unable to reproduce it and none of our clients do. We also have a couple of app on the App store but until now we didn't get any similar crash. 

If you could provide us with info on how to reproduce this it would be of a great help.

Regards

**Comment by khambir** [comment] 2019-12-10 09:46
The same issue. An application crashes with error `Called while no video data output'. 100% crashes happened in background for some reason... We use the latest update of your SDK.

**Comment by culoi** [comment] 2019-12-10 09:49
Hello @khambir,

Are you able to reproduce this on your end? 

Regards

**Comment by khambir** [comment] 2019-12-10 09:54
Hello @culoi. 

Unfortunately no. But I can see this crash from crashlytics and from our users. 

And the same crash I had before #157 . You can check it also (the same behavior), with the attached video.

**Comment by Cerovec** [comment] 2020-03-20 10:34
Hi @khambir,

Just to check - can we close this issue since you're already using v5.3?

Thanks,
Jurica.

**Comment by Cerovec** [comment] 2020-03-20 11:12
Sorry @khambir, @kikettas, @iSapozhnik, @donikv - I just realized this is a different issue and that this still might be happening in v5.3. Can you perform an upgrade and let us know if this still exists?

Thanks,
Jurica.

**Comment by khambir** [comment] 2020-03-20 11:17
@Cerovec I will give you feedback when I get analytics about crashes with a new version of the BlinkID. Because I can not reproduce this bug from my side, I can only see it in crashlitycs reports.

**Comment by Cerovec** [comment] 2020-03-24 17:45
Hi @khambir,

Excellent, we'll wait for your feedback in that case!

Thanks,
Jurica.

**Comment by Cerovec** [comment] 2020-04-13 19:40
Hi @khambir,

Do you have any updates with crash reports?

Thanks,
Jurica.

**Comment by khambir** [comment] 2020-04-13 19:50
Hi @Cerovec. It looks like this bug gone.

**Comment by Cerovec** [comment] 2020-04-14 12:22
Hi @khambir, 

That's great news! 

@kikettas, @iSapozhnik, @donikv - let us know if the new version works for you as well. If anyone needs to get new license keys for BlinkID v5, please let us know that at support@microblink.com.

I'm closing this issue for now, but if anything happens, we can reopen it once again.

Thanks,
Jurica.

**Closed by Cerovec** 2020-04-14 12:22 UTC
Labels: bug
