### ISSUE TITLE
Barcode scanner lag camera preview, call updateUI from background thread

### ISSUE THREAD

**Issue by identitytm** [BlinkID/blinkid-ios#141] opened 2018-02-22 12:00 UTC
Hello, 
I am using your sample pdf417-sample and there is a lag when your cameraViewController is presented.
Details:
I clicked "Scan" or "Custom UI", CameraViewController is presented but initial 1-1,5seconds view is black. After this delay camera preview is shown.

Can I somehow speed up showing camerapreview? Are you initialize camera and cameraPreview in viewDidAppear method? I do not like this lug :( 

Also after
[self presentViewController:scanningViewController animated:YES completion:nil];

Xcode is showing warning that 
runtime: UI API called from background thread: -[UIView frame] must be used from main thread only
runtime: UI API called from background thread: -[UIApplication statusBarOrientation] must be used from main thread only
etc.

Grzegorz Makowski

**Comment by culoi** [comment] 2018-02-22 15:15
Hi @identitytm 

You can try presenting the view controller without animation, since in the demo app by default it is presented with animation. 
>    [self presentViewController:alertController animated:YES completion:nil];

Regarding background thread, does this warning affect the scanning or it's simply annoying? 

We are aware of this, but this warning shouldn't affect scanning in any way. We have on our roadmap to fix this in our next releases.

Regards

**Comment by identitytm** [comment] 2018-02-23 09:37
no, without animation there is still lag. And I want to show controller animated.
Any ideas? It is a bug for me.

About background thread, that was just annoying. If you are aware and have it on your roadmap it's ok.

**Comment by culoi** [comment] 2018-02-23 10:05
@identitytm 

Can you please share which device did you use in your testing? 

Regards

**Comment by identitytm** [comment] 2018-02-23 12:39
@culoi sure, iphone 6s and ipad mini 4. Both iOS 11.2.

**Comment by culoi** [comment] 2018-02-23 15:50
@identitytm 

I'm sorry but we are unable to reproduce the issue where the camera is opening for more than 1 - 1,5 sec. Are you able to share a screen recording of the camera starting to support@microblink.com? 

Also, is this happening with other apps that are starting the camera internally, like Facebook, Instagram, etc?

Regards,

Ivan

**Comment by culoi** [comment] 2018-09-11 09:42
Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com

**Closed by culoi** 2018-09-11 09:42 UTC
