### ISSUE TITLE
Publish v1.4.0 Podspec

### ISSUE THREAD

**Issue by djtarazona** [BlinkID/blinkid-ios#21] opened 2016-05-04 22:01 UTC
Can you please public the v1.4.0 Podspec to CocoaPods?  It still shows v1.3.0 as the latest.

Thanks! :)

**Comment by Cerovec** [comment] 2016-05-05 12:12
CocoaPods repo unfortunately doesn't support git large file storage. The workaround at this point is to use Podfile which contents like this:

pod 'PPBlinkID', :git => 'https://github.com/blinkid/blinkid-ios', :branch => 'master'

We're looking into ways how to make git lfs work with public pod repository.

**Comment by djtarazona** [comment] 2016-05-05 16:44
Interesting. I'm curious, what uses Git LFS now compared to v1.3.0?

**Comment by Cerovec** [comment] 2016-05-05 18:08
Library size surpassed 100MB (now is 110MB), which is a limit given by github. Library size increased drastically when we introduced bytecode, but we believe it's important to have this available for all developers which use our SDK.

We're also considering moving to other repository hosting services (such as bitbucket), but we're also talking with cocoapods engineers and hopefully we'll have a solution for this soon :)

In the meantime, does the workaround work for you?

**Comment by djtarazona** [comment] 2016-05-05 18:26
Got it.  Yes, the workaround works fine.

PS: Don't move to BitBucket! :P

**Comment by bcbroom** [comment] 2016-05-13 18:36
I changed my Podfile to match the comment above, and now my project does not compile, with many errors about Blink objects without proper definitions.

I looked at MicroBlink.h, for example, and it shows

version https://git-lfs.github.com/spec/v1
oid sha256:39e01a7678ec1fe710e79b029773f76eecdd3c233db8d1360889ba0c8059fce0
size 786

Is there some other setting that is needed in the pod file?

**Comment by Pickles112358** [comment] 2016-05-16 15:43
Hello,

Could you try installing Git LFS as described here: https://git-lfs.github.com ?
This might fix your issue.

**Comment by superarts** [comment] 2016-05-23 04:19
I'm using `pod 0.39.0` and I have `pod 'PPBlinkID', :git => 'https://github.com/blinkid/blinkid-ios', :branch => 'master'` in my `Podfile`. Unfortunately, after `pod update`, `MicroBlink.framework` headers appears to be something like: 

```
version https://git-lfs.github.com/spec/v1
oid sha256:39e01a7678ec1fe710e79b029773f76eecdd3c233db8d1360889ba0c8059fce0
size 786
```

Reverting to `1.3.0` works fine. Any idea please?

**Comment by DrNeuroSurg** [comment] 2016-05-23 09:27
Same as "superparts" to me ...

**Comment by Cerovec** [comment] 2016-05-23 16:02
Hey superarts, DrNeuroSurg,

can you verify you have installed git-lfs using:

    brew install git-lfs

you can verifyi this by typing `git-lfs` in your terminal.

Kind regards,
Jurica.

**Comment by superarts** [comment] 2016-05-23 23:31
Thanks Jurica, I've installed `git-lfs` as suggested but got the same result.

**Comment by Pickles112358** [comment] 2016-05-24 11:38
Unfortunately, we are unable to recreate the issue at the time. Could you try removing pod related files in your project directory and do a fresh `pod install` or creating a new empty project? I am using pod version 0.39 with git-lfs installed and I have no issues.

Kind regards,
Dino

**Comment by bcbroom** [comment] 2016-05-24 12:37
I had the same issue after installing git-lfs. I still had the file "pointers" with dummy information. What I did was 

1. change my pod file back to the 'old' PPBlinkID (I think I removed the version number, but you might have to use '1.3.0' (I copied it to the clipboard so I could easily paste it back in later)
2. from the command line do 'pod update PPBlinkID'
3. in the output, you should see the BlinkID version change back to 1.3.0
4. Replace the pod file line for PPBlinkID (I had the specific branch from github, maybe you can just use 1.4.0 now - just paste in what you had in step 1.
5. Run 'pod update PPBlinkID' again
6. you should see the version change back to 1.4.0 in the pod output.

Then the header files had the correct contents. I'm assuming that the magic going on in git-lfs only works on the clone/import step, and since git-lfs was installed after the files were pulled, the files with the git-lfs pointers didn't automatically update to do the right thing. Hope that helps.

**Comment by bcbroom** [comment] 2016-05-24 12:38
Part of the issue is that there is no mention of 'git-lfs' on the setting up directions in the documentation.

**Comment by Pickles112358** [comment] 2016-06-29 16:23
The documentation has been updated and our CocoaPod now works with Git LFS.

**Closed by Pickles112358** 2016-06-29 16:23 UTC
