### ISSUE TITLE
Camera frame is small in iPhone SE and iPhone 5

### ISSUE THREAD

**Issue by chonex143** [BlinkID/blinkid-ios#80] opened 2017-05-16 10:04 UTC
Let me know how to fix this.

<img width="362" alt="screen shot 2017-05-16 at 6 01 19 pm" src="https://cloud.githubusercontent.com/assets/25475522/26100917/e8022f70-3a61-11e7-826d-7b7b329e89e4.png">

**Comment by juraskrlec** [comment] 2017-05-16 12:51
Hi @chonex143 
this is very specific use case for our default view controller. We suggest that you implement custom overlay view controller as your picture and use that custom overlay view controller. 

Best,
Jura

**Comment by Cerovec** [comment] 2017-05-17 23:19
Also - the frame is small because we designed it so that it doesn't overlay the light text and the text below the frame. If the frame would be larger - it would overlap.

Our default overlay is not designed to be used inside this kind of UX. You should definitely use custom UI approach here.

Let us know if you need any help with this.

**Comment by Cerovec** [comment] 2017-05-24 15:58
@chonex143 - please provide an update for this issue.

**Comment by Cerovec** [comment] 2017-05-31 13:34
Closing as not an issue - the UI is like this by design and this requires custom UI integration. 

Please reopen if additional help is need.

**Closed by Cerovec** 2017-05-31 13:34 UTC
