### ISSUE TITLE
Crash from background state.

### ISSUE THREAD

**Issue by khambir** [BlinkID/blinkid-ios#157] opened 2018-04-18 08:10 UTC
**Actions:**
1. Open scan screen
2. Lock device
3. Unlock device.

**Result:** App is crashed after device was unlocked.

[video.zip](https://github.com/BlinkID/blinkid-ios/files/1923024/video.zip)

Affected iOS (info from Crashlytics): iOS 10, 11.

Affected devices (info from Crashlytics): iPhone 7, 6s Plus, 6, 6 Plus, 5s.
Can not reproduce on iPhone 6s.

Crash insights (info from Crashlytics):

>  **OpenGL rendering while app in background state**
Based on the stack trace displayed here, it looks like new calls triggering OpenGL rendering took place while the app was transitioning to, or from, a background state.

**All crashes were in background state.**

```
Crashed: net.photopay.frame.processing
0  libGPUSupportMercury.dylib     0x19d659fac gpus_ReturnNotPermittedKillClient
1  AGXGLDriver                    0x1a2230e00 (Missing)
2  libGPUSupportMercury.dylib     0x19d65af88 gpusSubmitDataBuffers
3  AGXGLDriver                    0x1a223230c (Missing)
4  GLEngine                       0x1a29c1b14 glFinish_Exec
5  MicroBlink                     0x1007915f0 _hidden#10412_ + 799208
6  libdispatch.dylib              0x18c4f69a0 _dispatch_client_callout + 16
7  libdispatch.dylib              0x18c504ad4 _dispatch_queue_serial_drain + 928
8  libdispatch.dylib              0x18c4fa2cc _dispatch_queue_invoke + 884
9  libdispatch.dylib              0x18c506a50 _dispatch_root_queue_drain + 540
10 libdispatch.dylib              0x18c5067d0 _dispatch_worker_thread3 + 124
11 libsystem_pthread.dylib        0x18c6ff100 _pthread_wqthread + 1096
12 libsystem_pthread.dylib        0x18c6fecac start_wqthread + 4```

**Comment by khambir** [comment] 2018-04-23 07:27
Any updates?

**Comment by Pickles112358** [comment] 2018-04-24 10:58
Hi khambir,

We are unable to reproduce this issue on the latest version. Could you download the latest version (v2.17.2) and check if this issue persists?

**Comment by culoi** [comment] 2018-09-11 12:26
Closing the issue. Please reopen if you have additional question or contact us directly at support@microblink.com

**Closed by culoi** 2018-09-11 12:26 UTC
