### ISSUE TITLE
ignoring file ../../MicroBlink.framework/MicroBlink, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) on Xcode version 10.0

### ISSUE THREAD

**Issue by AbdoElabd** [BlinkID/blinkid-ios#211] opened 2018-10-24 09:43 UTC
### [READ] Step 1: Are you in the right place?

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with BlinkID tag.
  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Microblink support](https://help.microblink.com/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: _____
  * BlinkID SDK version: _____
  * What are you trying to scan? _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by culoi** [comment] 2018-10-24 10:58
Hello @AbdoElabd 

Did you [use pods](https://github.com/BlinkID/blinkid-ios#using-cocoapods) or did you [clone repo](https://github.com/BlinkID/blinkid-ios#integration-without-cocoapods)?

Regards

**Comment by AbdoElabd** [comment] 2018-10-24 11:04
Hello ,
i downloaded zip file and how to get  un*limited license key , please ?*


*Regards,*
*Abdelrahman Elabd*


*T.*    + (20) 01060615066
*E.    **e <hend.omar@its.ws>ngabdoelabd@gmail.com <ngabdoelabd@gmail.com>*

**Comment by culoi** [comment] 2018-10-24 11:10
Hello @AbdoElabd 

As our framework is over 100 MB in size, we use git-lfs to store the files. Please follow this steps to obtain working version of the SDK:

Install Git Large File Storage by running these comamnds:
`brew install git-lfs`
`git lfs install`

Be sure to restart your console after installing Git LFS

To clone, run the following shell command:

`git clone git@github.com:BlinkID/blinkid-ios.git`

Please let me know how it works for you. 

Also to obtain unlimited license key, please contact our Sales team (sales (at) microblink .com) with more information about your use-case.

Regards

**Comment by AbdoElabd** [comment] 2018-10-25 09:31
please send me Contacts of Our sales teams .
thanks alot.

*Regards,*
*Abdelrahman Elabd*

*Senior iOS*


*T.*    + (20) 01060615066
*E.    **e <hend.omar@its.ws>ngabdoelabd@gmail.com <ngabdoelabd@gmail.com>*

**Comment by AbdoElabd** [comment] 2018-10-30 09:36
I needed sample of Blink id applicate on any country to show how implement
protocol and get photo of id ,please .
thanks alot
*Regards,*
*Abdelrahman Elabd*

*Senior iOS *


*T.*    + (20) 01060615066
*E.    **e <hend.omar@its.ws>ngabdoelabd@gmail.com <ngabdoelabd@gmail.com>*

**Comment by culoi** [comment] 2018-10-30 09:39
Hello @AbdoElabd 

Please check out our Samples folder: https://github.com/BlinkID/blinkid-ios/tree/master/Samples

There are couple demo apps for different use-cases.

Regards

**Comment by AbdoElabd** [comment] 2018-10-30 09:44
i'm  not found specific  sample to take data from front Id of any specific
country , please send me any sample to take front id of any country .
thanks alot .
*Regards,*
*Abdelrahman Elabd*


*T.*    + (20) 01060615066
*E.    **e <hend.omar@its.ws>ngabdoelabd@gmail.com <ngabdoelabd@gmail.com>*

**Comment by AbdoElabd** [comment] 2018-10-30 09:47
please determine specific sample to deal front of ID . and extract data .
*Regards,*
*Abdelrahman Elabd*


*T.*    + (20) 01060615066
*E.    **e <hend.omar@its.ws>ngabdoelabd@gmail.com <ngabdoelabd@gmail.com>*

**Comment by culoi** [comment] 2018-10-30 10:00
Hello @AbdoElabd 

Can you please share the country of the ID that you are scanning?

Regards

**Comment by AbdoElabd** [comment] 2018-10-30 10:13
i 'm sorry for the many emails that i send to you and i hope to help me to
find of solution to solve this problem
Thanks.
*Regards,*
*Abdelrahman Elabd*

*Senior iOS*


*T.*    + (20) 01060615066
*E.    **e <hend.omar@its.ws>ngabdoelabd@gmail.com <ngabdoelabd@gmail.com>*

**Comment by AbdoElabd** [comment] 2018-10-30 13:55
I would to scan ID Bahrain or Kuit  please provide me a sample such as
application in app store .

*Regards,*
*Abdelrahman Elabd*


*T.*    + (20) 01060615066
*E.    **e <hend.omar@its.ws>ngabdoelabd@gmail.com <ngabdoelabd@gmail.com>*

**Comment by AbdoElabd** [comment] 2018-10-30 15:00
i needed a sample such as  application in app including custom view under
camera via .
[image: IMG_0450.PNG]
store
*Regards,*
*Abdelrahman Elabd*


*T.*    + (20) 01060615066
*E.    **e <hend.omar@its.ws>ngabdoelabd@gmail.com <ngabdoelabd@gmail.com>*

**Comment by AbdoElabd** [comment] 2018-10-30 15:15
please help me to solve problem .
*Regards,*
*Abdelrahman Elabd*


*T.*    + (20) 01060615066
*E.    **e <hend.omar@its.ws>ngabdoelabd@gmail.com <ngabdoelabd@gmail.com>*

**Comment by AbdoElabd** [comment] 2018-10-30 16:18
please reply to me .
*Regards,*
*Abdelrahman Elabd*


*T.*    + (20) 01060615066
*E.    **e <hend.omar@its.ws>ngabdoelabd@gmail.com <ngabdoelabd@gmail.com>*

**Comment by culoi** [comment] 2018-10-30 18:50
Hello,

In our BlinkIS-sample-Swift demo app: https://github.com/BlinkID/blinkid-ios/tree/master/Samples/BlinkID-sample-Swift you have to use MrtdCombinedRecognizer:http://blinkid.github.io/blinkid-ios/Classes/MBMrtdCombinedRecognizer.html
instead MBMrtdRecognizer
and instead MBDocumentOverlaySettings, you have to set MBDocumentVerificationOverlay: https://github.com/BlinkID/blinkid-ios/blob/master/README.md#mbdocumentverificationoverlayviewcontroller

Please test it out and let me know how it works for you.

Regards

**Comment by AbdoElabd** [comment] 2018-10-31 13:41
Abdelrahman Elabd <engabdoelabd@gmail.com>
[image: Attachments]15:15 (25 minutes ago)
to
*reply+022ed32bd8db1194e8d02f9979d61c08ec48edb0590e969592cf0000000117f1653492a169ce16687092*
i needed to add
*let* fullResultViewController = FullResultViewController()

documentVerificationOverlayViewController.present(fullResultViewController,
animated: *true*)

insteaded

let alertController: UIAlertController = UIAlertController.init(title:
title, message: message, preferredStyle: UIAlertControllerStyle.alert)

            let okAction: UIAlertAction = UIAlertAction.init(title:
"OK", style: UIAlertActionStyle.default,
                                                             handler:
{ (action) -> Void in

self.dismiss(animated: true, completion: nil)
            })
            alertController.addAction(okAction)

documentVerificationOverlayViewController.present(alertController,
animated: true, completion: nil)



to transfer data another viewController to show data to client such as
image that attached.
*Regards,*
*Abdelrahman Elabd*


*T.*    + (20) 01060615066
*E.    **e <hend.omar@its.ws>ngabdoelabd@gmail.com <ngabdoelabd@gmail.com>*

**Comment by jcular** [comment] 2018-11-01 08:50
Closed because it's a duplicate of #214

**Closed by jcular** 2018-11-01 08:50 UTC
