### ISSUE TITLE
Mach-O Linker error

### ISSUE THREAD

**Issue by mvayngrib** [BlinkID/blinkid-ios#48] opened 2016-12-27 03:20 UTC
getting this when running the BlinkID-sample from XCode 8.1, iOS 10.1.1

the OCR sample doesn't have this issue

```
ld: warning: ignoring file ../../MicroBlink.framework/MicroBlink, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): ../../MicroBlink.framework/MicroBlink
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_PPImageMetadata", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPCroIDFrontRecognizerResult", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPEudlRecognizerResult", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPUsdlRecognizerResult", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPCroIDBackRecognizerResult", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPViewControllerFactory", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPMrtdRecognizerSettings", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPMrtdRecognizerResult", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPSettings", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPMyKadRecognizerResult", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_PPCameraCoordinator", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by DoDoENT** [comment] 2016-12-27 14:51
Duplicate of #25 and #27.

**Closed by DoDoENT** 2016-12-27 14:51 UTC
