### ISSUE TITLE
Crash: Fatal Exception: NSGenericException *** -[AVCaptureSession stopRunning] stopRunning may not be called between calls to beginConfiguration and commitConfiguration

### ISSUE THREAD

**Issue by yakobz** [BlinkID/blinkid-ios#266] opened 2019-10-01 10:26 UTC
* Xcode version: 10.3
  * BlinkID SDK version: 4.9.1
  * What are you trying to scan? I don't know, we can't reproduce this issue on test environment. We allow users to scan driver license, ID and passport for UK.

This crash reproduces only on prod for real users, we can't reproduce this crash on test environment

I can attach crash report, but I don't have dSyms, so it unsymbolicated.

**Comment by culoi** [comment] 2019-10-01 10:33
Hi @yakobz,

Please provide us as much information as possible, together with the crash report. It would also be helpful for us to see how did you implement the scanning, so if you could share the code snippet it would be great.

You can also contact us directly at support@microblink.com (if you don't want to share the code publicly). 

Regards

**Comment by VitaliyGozhenko** [comment] 2019-10-21 08:36
Same thing for BlinkdID SDK 4.8. But crash happens only in iOS 10 for me

**Comment by culoi** [comment] 2019-11-04 12:42
Hi @VitaliyGozhenko @prasoonpuri12 

Can you please let us know how can we reproduce this crash?

Which recognizers and settings are you using? 

Best

**Comment by Cerovec** [comment] 2020-03-20 11:13
Hi @yakobz, @VitaliyGozhenko, @prasoonpuri12,

Can we ask you to check if this issue still happens on v5.3?

Thank you,
Jurica.

**Comment by Cerovec** [comment] 2020-04-06 15:12
Hi @yakobz, @VitaliyGozhenko, @prasoonpuri12,

Do you have any news about this issue?

We appreciate your help!
Jurica.

**Comment by Cerovec** [comment] 2020-04-07 19:17
Hi @yaakovgamliel 

It should not be a problem to get a valid license for v5, especially if you'll continue using the same features. I can help you out if you contact support at microblink.com.

Regarding the crash. It's not 100% clear how it would happen. 

But, the issue is that `[AVCaptureSession stopRunning]` is obviously being called between 
`beginConfiguration` and `commitConfiguration`. `stopRunning` is called every time you call `pauseCamera`, while `beginConfiguration` and `commitConfiguration` are called everytime you call `resumeCamera`. 

My best guess is that we have a race condition which causes the first one to be called while the other is in progress. 

At first glance it seems to me like that the calls to `pauseCamera` and `resumeCamera` are synchronized on the main queue. Do you think the same? Are there any other calls to `pauseCamera` and `resumeCamera`?

Thanks,
Jurica.

**Comment by Cerovec** [comment] 2020-04-17 05:23
Hi @yaakovgamliel,

Do you have any news about this?
Can we help you to obtain new license keys?

Thanks,
Jurica.

**Comment by yaakovgamliel** [comment] 2020-04-17 06:11
We can’t do an upgrade right now since it requires migration work, v5 has quite some breaking changes we will probably work on it next week since we continue to see this crash in production, the migration is not an easy task specially since most of the docs still have examples from previous versions.

**Comment by Cerovec** [comment] 2020-04-19 15:32
Hi @yaakovgamliel,

Thanks for the update. Can we jump to a short call before you start the upgrade? I’d want to understand which challenges you face. This will help us to improve the docs and examples for all other developers who face the same challenge.

Thanks,
Jurica.

**Comment by yaakovgamliel** [comment] 2020-04-19 15:50
Sure, I may do some work this week I’ll post the code we have for it here.

**Comment by dingwilson** [comment] 2022-08-22 19:22
Hello! Are there any updates here? Do we know if newer versions mitigate this crash?

**Comment by prasoonpuri12** [comment] 2022-08-23 13:03
Hi,

Yes we had not experienced this issue new newer version of Blink ID. You
can close the ticket. Thanks.

Regards,
Prasoon Puri

**Comment by mparadina** [comment] 2022-08-23 13:57
Hi @dingwilson and @prasoonpuri12 

Yes, this was fixed in later versions of the SDK.
I suggest trying out the current latest version, [5.18.0](https://github.com/BlinkID/blinkid-ios/releases/tag/v5.18.0), on your side to confirm if the issue was resolved.

Let me know if you have any additional questions.

**Comment by mparadina** [comment] 2022-08-26 08:53
Hi @dingwilson and @prasoonpuri12 

Is it alright to close the issue?
If anything comes up related to the topic, you can always reopen the issue or create a new one.

**Comment by prasoonpuri12** [comment] 2022-08-26 08:54
Yes, it is working. Please close it

**Comment by mparadina** [comment] 2022-08-26 09:48
@prasoonpuri12 thank you for the feedback!

Closing the issue.

**Closed by mparadina** 2022-08-26 09:48 UTC
Labels: bug, question
